# Tutorials say this should work. gcloud sdk says it shouldn't be there and use a specific project as current project.
# See why this discrepancy is there.
#application: bookie
#version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /.*
  script: bookie.wsgi.application

- url: /_ah/(mapreduce|queue|warmup).*
  script: bookie.wsgi.application
  login: admin

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

libraries:

- name: django
  version: "1.9"

- name: ssl
  version: latest